export const publicRoutes = [
  "/",
  "/shop",
  "/how-it-works",
  "/industries",
  "/guides",
  "/faq",
  "/setup",
  "/nfc-compatibility",
  "/tools/google-review-link-generator",
  "/collections/review-stands",
  "/collections/review-cards",
  "/collections/review-stickers",
  "/collections/bundles",
  "/platforms/google",
  "/platforms/instagram",
  "/platforms/facebook",
  "/platforms/yelp",
  "/contact",
  "/track-order",
  "/privacy-policy",
  "/terms",
] as const;
